### ISSUE TITLE
Create "embed-able" version for CMS integration

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/climatechangeisreal#3]
Some cities have noted that they cannot build a standalone version of the "climatechangeisreal" website because of limitations and the need to integrate it into their CMS.

The objective is to create a version that can be embedded into other websites using something simple like an `<iframe>` tag. For most CMS platforms, cities can create a single webpage that simply contains an iframe.

My initial approach will be to deploy the webpages from GitHub to AWS S3 instance. S3 can [host static webpages](http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html). Will use Travis CI to detect changes in GitHub and copy files to S3.

**Comment by tomschenkjr** [comment]
Currently testing this on the `dev` branch.

**Comment by tomschenkjr** [comment]
The demo of the site is now at http://climatechangeisreal.s3-website.us-east-2.amazonaws.com/. Others should be able to embed this webpage. 

Remaining to-do's:

- [ ] Setup the automated process to push from GitHub to AWS
- [x] Provide documentation in the README on this. _README updated on `master` branch_

@chrisjcalderon - I'm going to edit the `branding/` folders to make it even more generic so it displays nicely on AWS.

**Comment by mkeKT** [comment]
Here's what Milwaukee has so far: milwaukee.gov/sustainability/About-Us/Climate-Change.htm. Could you eliminate .header-content on your end? On my end .header-content { display: none; } doesn't work because it's an iframe. THANKS!
