### ISSUE TITLE
List of cities hosting climatechangeisreal

### ISSUE THREAD

**Issue by bencooper222** [Chicago/climatechangeisreal#4]
It'd be awesome if we could see which cities have decided to add this to their site - maybe a `city.md`?

**Comment by tomschenkjr** [comment]
Leaving this here for a moment as a note to self

* [Atlanta, GA](http://www.atlantaga.gov/index.aspx?page=18)
* [Boston, MA](http://climatechangedata.boston.gov/)
* [Burlington, VT](https://climatechange.burlingtonvt.gov)
* [Evanston, IL](http://cityofevanston.org/climatechangeisreal)
* [Fayetteville, AR](http://www.fayetteville-ar.gov/3281/Climate-Change)
* [Houston, TX](http://www.greenhoustontx.gov/climate-change-is-real.html)
* [Milwaukee, WI](http://milwaukee.gov/ClimateChangeIsReal)
* [New Orleans, LA](http://climatechange.nola.gov/)
* [Philadelphia, PA](http://beta.phila.gov/climatechangeisreal)
* [Portland, OR](http://www.portlandoregon.gov/bps/climatechangeisreal)
* [San Francisco, CA](http://epaclimatechange.sfgov.org/)
* [Seattle, WA](http://seattle.gov/climatechangeisreal)
* [St. Louis, MO](https://climatechange.stlouis-mo.gov/)
